name: Lint
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn

      - name: lint
        run: yarn run lint
