name: Test CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: lint
        run: npm run lint
      - name: test
        run: npm test -- --coverage
      - name: build
        run: npm run build
      - name: Generate coverage
        run: bash <(curl -s https://codecov.io/bash)
